# Generated by Django 2.2 on 2020-06-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(default='1234', max_length=200)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('phone_no', models.CharField(default=' ', max_length=20)),
                ('photo', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(default='1234', max_length=200)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('phone_no', models.CharField(default=' ', max_length=20)),
                ('photo', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
