# Generated by Django 2.2 on 2020-06-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='doctors',
            name='speciality',
            field=models.CharField(default='doctor', max_length=200),
        ),
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patients',
            name='blood',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
