# Generated by Django 2.2 on 2020-06-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200618_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='speciality',
            new_name='department',
        ),
    ]
