# Generated by Django 2.2 on 2020-06-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200623_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='experience',
        ),
    ]
