# Generated by Django 2.2 on 2020-06-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_auto_20200618_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=200)),
                ('payment_status', models.CharField(default='Pending', max_length=200)),
                ('disease', models.CharField(blank=True, max_length=200)),
                ('report', models.CharField(blank=True, max_length=200)),
                ('prescription', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='Active', max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patients')),
            ],
        ),
    ]
