# Generated by Django 2.2 on 2020-06-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_data',
            name='prescription',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='appointment_data',
            name='problem',
            field=models.CharField(max_length=1000),
        ),
    ]
