# Generated by Django 2.2 on 2020-06-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_data_time_of_registring_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_data',
            name='doctor_approval',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment_data',
            name='doctor_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appointment_data',
            name='is_modify_by_doc',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment_data',
            name='receptionist_approval',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment_data',
            name='receptionist_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
