# Generated by Django 2.2 on 2020-06-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200623_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment_data',
            old_name='disease',
            new_name='before_disease',
        ),
    ]
