# Generated by Django 2.2 on 2020-06-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20200624_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_data',
            name='after_disease',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
