# Generated by Django 2.2 on 2020-06-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20200625_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment_data',
            old_name='doctor_approval',
            new_name='doctor_response',
        ),
    ]
